-- Cars With Fares — Command Center · Postgres schema (Phase 1)
-- Multi-tenant-READY: every table carries business_id (default 1 = Cars With Fares).
-- One business today; Skyline later = insert one businesses row + a workspace switcher. No schema change.

BEGIN;

-- ---------- tenants ----------
CREATE TABLE businesses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT UNIQUE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- enums ----------
CREATE TYPE job_status  AS ENUM ('lead','quoted','scheduled','in_progress','completed','paid','lost');
CREATE TYPE ai_band     AS ENUM ('hot','warm','cold');
CREATE TYPE task_kind   AS ENUM ('follow_up','review_ask','referral','nudge','todo');
CREATE TYPE task_status AS ENUM ('open','done','dismissed');

-- ---------- customers ----------
CREATE TABLE customers (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id      BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  name             TEXT,
  phone            TEXT,
  phone_normalized TEXT,                 -- last-10 digits; used for dedup
  email            TEXT,
  location         TEXT,
  source           TEXT,                 -- site form, manual, paste, voice, referral...
  notes            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- one customer per phone per business; no-phone leads never collide (partial index)
CREATE UNIQUE INDEX customers_business_phone_uq
  ON customers (business_id, phone_normalized)
  WHERE phone_normalized IS NOT NULL;
CREATE INDEX customers_business_idx ON customers (business_id);

-- ---------- vehicles ----------
CREATE TABLE vehicles (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  customer_id  BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  year         INT,
  make         TEXT,
  model        TEXT,
  vin          TEXT,
  is_euro      BOOLEAN NOT NULL DEFAULT false,   -- euro-specialist flag (BMW/Audi/MB/VW...)
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX vehicles_customer_idx ON vehicles (customer_id);
CREATE INDEX vehicles_business_idx ON vehicles (business_id);

-- ---------- jobs (the pipeline) ----------
CREATE TABLE jobs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id      BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  customer_id      BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  vehicle_id       BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  status           job_status NOT NULL DEFAULT 'lead',
  issue            TEXT,                 -- symptom-first description
  service          TEXT,
  source           TEXT,
  est_value        NUMERIC(10,2),        -- expected ticket
  charge           NUMERIC(10,2),        -- final flat price (NO tax line — Fares is unregistered)
  parts_cost       NUMERIC(10,2),
  gas_cost         NUMERIC(10,2),
  est_profit       NUMERIC(10,2),        -- charge - parts_cost - gas_cost (computed on write)
  is_high_ticket   BOOLEAN NOT NULL DEFAULT false,
  ai_score         INT,                  -- 0-100
  ai_band          ai_band,
  ai_nba           TEXT,                 -- next-best-action, one line
  quote_text       TEXT,                 -- the clipboard quote blob (tax-free)
  first_contact_at TIMESTAMPTZ,          -- speed-to-lead denominator (stamped on first call/text)
  scheduled_date   DATE,
  lost_reason      TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  paid_at          TIMESTAMPTZ
);
CREATE INDEX jobs_business_status_idx ON jobs (business_id, status);
CREATE INDEX jobs_first_contact_idx   ON jobs (first_contact_at);
CREATE INDEX jobs_created_idx         ON jobs (created_at);

-- ---------- activity (the timeline) ----------
CREATE TABLE activity (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  job_id       BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  customer_id  BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  type         TEXT NOT NULL,            -- call, text, note, status_change, ai_draft, quote, system
  body         TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX activity_job_idx      ON activity (job_id, created_at);
CREATE INDEX activity_business_idx ON activity (business_id, created_at);

-- ---------- tasks (the un-droppable follow-up engine — one table, planning + follow-ups) ----------
CREATE TABLE tasks (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  job_id       BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  customer_id  BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  kind         task_kind NOT NULL DEFAULT 'todo',
  title        TEXT NOT NULL,
  body         TEXT,                     -- e.g. the drafted review/referral/follow-up text
  status       task_status NOT NULL DEFAULT 'open',
  due_at       TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);
CREATE INDEX tasks_business_status_idx ON tasks (business_id, status, due_at);
CREATE INDEX tasks_job_idx             ON tasks (job_id);

-- ---------- leads_radar (Reddit interception queue — find → draft → YOU send) ----------
CREATE TABLE leads_radar (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  source       TEXT NOT NULL DEFAULT 'reddit',
  external_id  TEXT,                     -- reddit fullname t3_xxx (dedup)
  subreddit    TEXT,
  url          TEXT,
  title        TEXT,
  body         TEXT,
  score        INT,                      -- relevance 0-100
  draft_reply  TEXT,                     -- trust-led, rules-respecting draft (you send)
  status       TEXT NOT NULL DEFAULT 'new',  -- new, sent, dismissed
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX leads_radar_source_ext_uq ON leads_radar (source, external_id) WHERE external_id IS NOT NULL;
CREATE INDEX leads_radar_business_status_idx   ON leads_radar (business_id, status, score DESC);

-- ---------- traffic (funnel inputs for the Targets board) ----------
CREATE TABLE traffic (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id  BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  day          DATE NOT NULL,
  views        INT NOT NULL DEFAULT 0,
  contacts     INT NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (business_id, day)
);

-- ---------- settings (key/value per business: targets, activation flags, cached briefing) ----------
CREATE TABLE settings (
  business_id  BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id),
  key          TEXT NOT NULL,
  value        JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (business_id, key)
);

-- ---------- updated_at trigger ----------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER customers_updated BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER jobs_updated      BEFORE UPDATE ON jobs      FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------- seed: the one business + sane defaults (from the blueprint) ----------
INSERT INTO businesses (id, name, slug) VALUES (1, 'Cars With Fares', 'cwf');
SELECT setval(pg_get_serial_sequence('businesses','id'), 1, true);

INSERT INTO settings (business_id, key, value) VALUES
  (1, 'targets',      '{"avg_ticket":925,"goal_monthly_revenue":4800,"goal_jobs_per_week":3.5}'::jsonb),
  (1, 'activation',   '{"twilio":false,"google_ads":false,"ga4":false,"review_texts_sent":false}'::jsonb),
  (1, 'profit_floor', '{"min_profit":1000}'::jsonb);

COMMIT;
