// DB bootstrap + idempotent migrations. Runs on every boot.
// Fresh DB: applies schema.sql. Always: runs IF-NOT-EXISTS migrations so existing DBs converge.
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import pg from 'pg'

const { Pool } = pg
const here = dirname(fileURLToPath(import.meta.url))

const MIGRATIONS = [
  `alter table jobs add column if not exists ticket_tier text`,
  `alter table jobs add column if not exists likely_cause text`,
  `alter table jobs add column if not exists safety_flag boolean default false`,
  `alter table jobs add column if not exists follow_up_at timestamptz`,
  `create table if not exists activation (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     sort int default 0, key text not null, label text not null,
     status text not null default 'todo', unlocks text, doc_link text,
     updated_at timestamptz not null default now(),
     unique (business_id, key))`,
  `insert into activation (business_id,sort,key,label,status,unlocks,doc_link) values
     (1,1,'reviews','Send the 2 review-ask texts (Rob + George)','todo','#1 Google Maps ranking lever','business-templates/customer-followup-scripts.md'),
     (1,2,'google_ads','Connect Google Ads + launch the campaign','todo','Fastest tap for high-ticket leads','strategy/google-ads-campaign.md'),
     (1,3,'twilio','Connect Twilio (3 secrets)','todo','Instant speed-to-lead auto-text','strategy/speed-to-lead.md'),
     (1,4,'ga4','Mark GA4 generate_lead a Key Event','todo','Conversion tracking + Ads optimization',''),
     (1,5,'gbp','Optimize Google Business Profile (photos)','todo','Local Google Maps visibility','strategy/gbp-local-seo.md'),
     (1,6,'content','Post the 28 content scripts','todo','Cheapest organic reach','strategy/content-plan-v2.md'),
     (1,7,'retell','Connect Retell + ElevenLabs','todo','AI phone advisor for missed calls','ai-phone-agent/AGENT-PROMPT.md')
     on conflict (business_id,key) do nothing`,
  `insert into settings (business_id,key,value)
     values (1,'growth_targets','{"target_revenue":4800,"avg_ticket":925,"target_jobs":5,"target_contacts":40,"target_views":2000}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `update jobs set ticket_tier = case
     when coalesce(charge,est_value,0) >= 700
       or issue ~* 'suspension|control arm|ball joint|engine|transmission|clutch|alternator|timing|head gasket|strut|shock|no.?start|axle|differential|turbo|rack|cv|rebuild'
     then 'HIGH' else 'STANDARD' end
   where ticket_tier is null`,
]

export async function applySchema() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.PGSSL === 'disable' ? false : { rejectUnauthorized: false },
  })
  try {
    let up = false
    for (let i = 0; i < 20 && !up; i++) {
      try { await pool.query('select 1'); up = true }
      catch { await new Promise((r) => setTimeout(r, 3000)) }
    }
    if (!up) { console.error('[schema] DB not reachable — skipping'); return }

    const present = await pool.query("select to_regclass('public.businesses') as t")
    if (!present.rows[0].t) {
      const sql = readFileSync(join(here, '..', '..', 'db', 'schema.sql'), 'utf8')
      await pool.query(sql)
      console.log('[schema] applied + seeded ✓')
    } else {
      console.log('[schema] base present')
    }
    for (const m of MIGRATIONS) {
      try { await pool.query(m) } catch (e) { console.error('[migrate] ' + e.message) }
    }
    console.log('[migrate] done ✓')
  } catch (e) {
    console.error('[schema] error:', e.message)
  } finally {
    await pool.end()
  }
}
