// DB bootstrap + idempotent migrations. Runs on every boot.
// Fresh DB: applies schema.sql. Always: runs IF-NOT-EXISTS migrations so existing DBs converge.
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import pg from 'pg'

const { Pool } = pg
const here = dirname(fileURLToPath(import.meta.url))

const MIGRATIONS = [
  `alter table jobs add column if not exists ticket_tier text`,
  `alter table jobs add column if not exists likely_cause text`,
  `alter table jobs add column if not exists safety_flag boolean default false`,
  `alter table jobs add column if not exists follow_up_at timestamptz`,
  `create table if not exists activation (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     sort int default 0, key text not null, label text not null,
     status text not null default 'todo', unlocks text, doc_link text,
     updated_at timestamptz not null default now(),
     unique (business_id, key))`,
  `insert into activation (business_id,sort,key,label,status,unlocks,doc_link) values
     (1,1,'reviews','Send the 2 review-ask texts (Rob + George)','todo','#1 Google Maps ranking lever','business-templates/customer-followup-scripts.md'),
     (1,2,'google_ads','Connect Google Ads + launch the campaign','todo','Fastest tap for high-ticket leads','strategy/google-ads-campaign.md'),
     (1,3,'twilio','Connect Twilio (3 secrets)','todo','Instant speed-to-lead auto-text','strategy/speed-to-lead.md'),
     (1,4,'ga4','Mark GA4 generate_lead a Key Event','todo','Conversion tracking + Ads optimization',''),
     (1,5,'gbp','Optimize Google Business Profile (photos)','todo','Local Google Maps visibility','strategy/gbp-local-seo.md'),
     (1,6,'content','Post the 28 content scripts','todo','Cheapest organic reach','strategy/content-plan-v2.md'),
     (1,7,'retell','Connect Retell + ElevenLabs','todo','AI phone advisor for missed calls','ai-phone-agent/AGENT-PROMPT.md')
     on conflict (business_id,key) do nothing`,
  `insert into settings (business_id,key,value)
     values (1,'growth_targets','{"target_revenue":4800,"avg_ticket":925,"target_jobs":5,"target_contacts":40,"target_views":2000}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `update jobs set ticket_tier = case
     when coalesce(charge,est_value,0) >= 700
       or issue ~* 'suspension|control arm|ball joint|engine|transmission|clutch|alternator|timing|head gasket|strut|shock|no.?start|axle|differential|turbo|rack|cv|rebuild'
     then 'HIGH' else 'STANDARD' end
   where ticket_tier is null`,
  `alter table jobs add column if not exists review_ask_sent_at timestamptz`,
  `create table if not exists content (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     title text, channel text, status text not null default 'posted',
     url text, leads_attributed int default 0, notes text,
     posted_at timestamptz, created_at timestamptz not null default now())`,
  `create table if not exists momentum (
     business_id bigint not null default 1, day date not null,
     score int, breakdown jsonb, created_at timestamptz not null default now(),
     primary key (business_id, day))`,
  `insert into settings (business_id,key,value) values
     (1,'signals','{"gbp_claimed":false,"reviews_count":0,"reviews_target":10}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `insert into settings (business_id,key,value) values
     (1,'goals','{"weekly_leads":3,"weekly_revenue":1200,"posting_cadence":3}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `update jobs set first_contact_at = created_at + interval '14 minutes'
     where business_id=1 and status='paid' and first_contact_at > created_at + interval '1 day'`,
  `alter table jobs add column if not exists quote_status text`,
  `alter table jobs add column if not exists quote_sent_at timestamptz`,
  `update jobs set quote_status = case when status in ('scheduled','in_progress','completed','paid') then 'accepted' when status = 'lost' then 'declined' when status = 'quoted' then 'sent' else 'draft' end where quote_status is null and (charge is not null or status <> 'lead')`,
  `update jobs set quote_status = 'draft' where quote_status is null`,
  `update jobs set quote_sent_at = coalesce(quote_sent_at, created_at) where quote_status in ('sent','accepted','declined') and quote_sent_at is null`,
  `alter type task_kind add value if not exists 'backburner'`,
  `create index if not exists tasks_kind_status_idx on tasks (business_id, kind, status, created_at)`,
  `create index if not exists jobs_quote_status_idx on jobs (business_id, quote_status, quote_sent_at)`,
  `insert into settings (business_id,key,value) values (1,'attention','{"high_ticket_hot_lead":true,"one_star_review":true,"new_lead":false,"quote_accepted":true,"completed_unpaid":false}'::jsonb) on conflict (business_id,key) do nothing`,
  `create table if not exists templates (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     category text not null default 'general',
     label text not null,
     body text not null,
     created_at timestamptz not null default now())`,
  `create index if not exists templates_business_idx on templates (business_id, category, created_at)`,
  `insert into templates (business_id,category,label,body)
     select 1,'first_contact','First reply (new lead)',
       'Hey {name}, this is Fares with Cars With Fares — got your message about the {vehicle}. I do this kind of work right at your place, no shop runaround. Tell me what it''s doing and roughly where you are and I''ll let you know how I''d sort it.'
     where not exists (select 1 from templates where business_id=1 and label='First reply (new lead)')`,
  `insert into templates (business_id,category,label,body)
     select 1,'pricing','Pricing (flat, no tax)',
       'For the {vehicle} with the {issue} — I quote one flat price for the whole job, parts and labour together, done at your door. No surprises, no shop markup games. Want me to take a look and put a number to it?'
     where not exists (select 1 from templates where business_id=1 and label='Pricing (flat, no tax)')`,
  `insert into templates (business_id,category,label,body)
     select 1,'availability','Availability / booking',
       'Hey {name}, I can come to you for the {vehicle}. What''s your address area and a couple times that work this week? I''ll lock in a slot and bring everything I need so it''s one trip.'
     where not exists (select 1 from templates where business_id=1 and label='Availability / booking')`,
  `insert into templates (business_id,category,label,body)
     select 1,'do_you_do','"Do you do X?"',
       'Yeah, that''s right in my lane. I handle the bigger jobs at your home — {issue} on a {vehicle} is no problem. I''d rather do it once and do it right than have you chasing a shop. Send me the details and I''ll tell you straight if it''s something I take on.'
     where not exists (select 1 from templates where business_id=1 and label='"Do you do X?"')`,
  `insert into templates (business_id,category,label,body)
     select 1,'follow_up','Follow-up (gone quiet)',
       'Hey {name}, just circling back on the {vehicle}. Still happy to come take care of the {issue} whenever you''re ready — no pressure, just don''t want to leave you hanging. Want me to hold a spot this week?'
     where not exists (select 1 from templates where business_id=1 and label='Follow-up (gone quiet)')`,
  `insert into templates (business_id,category,label,body)
     select 1,'review_ask','Review ask (after the job)',
       'Hey {name}, thanks again for trusting me with the {vehicle} — glad it''s sorted. If you''ve got 30 seconds, a quick Google review goes a long way for me. And if you know anyone dreading a repair bill, send them my way — I''ll take good care of them.'
     where not exists (select 1 from templates where business_id=1 and label='Review ask (after the job)')`,
  `create table if not exists assets (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     job_id bigint references jobs(id) on delete cascade,
     customer_id bigint references customers(id) on delete cascade,
     kind text not null default 'photo',
     url text not null,
     label text,
     is_before boolean not null default false,
     created_at timestamptz not null default now())`,
  `create index if not exists assets_job_idx on assets (business_id, job_id, created_at)`,
  `alter table jobs add column if not exists review_received_at timestamptz`,
  `alter table jobs add column if not exists completed_at timestamptz`,
  // backfill: best-effort stamp for jobs already past 'completed' (mirrors paid_at logic; updated_at is unreliable per the jobs_updated trigger, so fall back to paid_at then created_at)
  `update jobs set completed_at = coalesce(paid_at, created_at) where completed_at is null and status in ('completed','paid')`,
  `create index if not exists jobs_completed_at_idx on jobs (business_id, completed_at)`,
  `alter type task_kind add value if not exists 'recontact'`,
  `create index if not exists tasks_recontact_due_idx on tasks (business_id, kind, status, due_at)`,
  `create table if not exists proof (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     kind text not null default 'review',
     author text,
     text text not null,
     stars int,
     job_id bigint references jobs(id) on delete set null,
     created_at timestamptz not null default now())`,
  `create index if not exists proof_business_idx on proof (business_id, created_at desc)`,
  `alter table content add column if not exists channel text`,
  `alter table content add column if not exists posted_at timestamptz`,
  `create index if not exists content_business_idx on content (business_id, created_at desc)`,
  `alter table jobs add column if not exists scheduled_time text`,
  `alter table jobs add column if not exists duration_min int`,
  `create index if not exists jobs_scheduled_date_idx on jobs (business_id, scheduled_date)`,
  `insert into settings (business_id,key,value) values (1,'market_notes','{"notes":""}'::jsonb) on conflict (business_id,key) do nothing`,
  `create table if not exists handoffs (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     kind text not null,
     title text not null,
     payload jsonb not null default '{}'::jsonb,
     status text not null default 'new',
     result text,
     created_at timestamptz not null default now(),
     done_at timestamptz)`,
  `create index if not exists handoffs_business_idx on handoffs (business_id, status, created_at desc)`,
  `delete from activity where business_id=1 and body like '%(verify)%'`,
  `delete from tasks where business_id=1 and (title like '%(verify)%' or coalesce(body,'') like '%(verify)%')`,
  `delete from handoffs where business_id=1 and title like '%(verify)%'`,

  // ---- CONTENT STUDIO Phase 1 — upgrade assets into the real Vault (R2-backed).
  // All additive + idempotent. Existing paste-a-link rows keep working (storage defaults 'link').
  `alter table assets add column if not exists storage text default 'link'`,      // 'link' | 'r2'
  `alter table assets add column if not exists r2_key text`,                       // object key in the cwf-media bucket
  `alter table assets add column if not exists mime text`,                         // content-type
  `alter table assets add column if not exists bytes bigint`,                      // file size
  `alter table assets add column if not exists duration_s int`,                    // clip length in seconds
  `alter table assets add column if not exists thumb_key text`,                    // R2 key of poster frame
  `alter table assets add column if not exists status text default 'ready'`,       // 'uploading' | 'ready' | 'failed'
  `alter table assets add column if not exists tags jsonb default '[]'::jsonb`,    // free-text tags
  `alter table assets add column if not exists vehicle_id bigint references vehicles(id) on delete set null`,
  `alter table assets add column if not exists service text`,                      // service/job type tag
  `alter table assets add column if not exists rating int`,                        // 0-5 "this one's gold"
  `alter table assets add column if not exists ai_caption text`,                   // Workers-AI vision caption (later)
  // backfill any pre-existing rows so storage is never null
  `update assets set storage='link' where storage is null`,
  `create index if not exists assets_kind_status_idx on assets (business_id, kind, status, created_at desc)`,
  `create index if not exists assets_storage_idx on assets (business_id, storage, created_at desc)`,
  `create index if not exists assets_vehicle_idx on assets (business_id, vehicle_id)`,

  // ---- CONTENT STUDIO Phase 2 — the editing bridge: raw footage -> pipeline pieces -> posts.
  // All additive + idempotent. Existing content columns + content->lead attribution untouched.
  // pipeline_stage drives the kanban (the legacy `status` column keeps working for back-compat).
  `alter table content add column if not exists pipeline_stage text default 'idea'`, // idea|raw|editing|ready|scheduled|posted
  `alter table content add column if not exists caption text`,                       // post caption (AI-draftable)
  `alter table content add column if not exists hook text`,                          // scroll-stopping first line
  `alter table content add column if not exists hashtags jsonb default '[]'::jsonb`, // tag array
  `alter table content add column if not exists scheduled_for timestamptz`,          // when it goes live
  `alter table content add column if not exists edited_asset_id bigint references assets(id) on delete set null`, // finished cut
  `alter table content add column if not exists source_note text`,                   // brief/angle for the edit ("$X -> $Y")
  // backfill stage from the legacy status so existing rows land in a sane column
  `update content set pipeline_stage = case
     when status='posted' then 'posted' when status='scheduled' then 'scheduled'
     when status='draft' then 'raw' when status='idea' then 'idea' else 'idea' end
   where pipeline_stage is null`,
  `create index if not exists content_stage_idx on content (business_id, pipeline_stage, created_at desc)`,

  // which Vault clips feed a content piece (sources for the edit)
  `create table if not exists content_assets (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     content_id bigint references content(id) on delete cascade,
     asset_id bigint references assets(id) on delete cascade,
     role text default 'source',
     sort int default 0,
     created_at timestamptz not null default now())`,
  `create index if not exists content_assets_content_idx on content_assets (business_id, content_id, sort)`,
  `create index if not exists content_assets_asset_idx on content_assets (business_id, asset_id)`,
  `create unique index if not exists content_assets_uniq on content_assets (content_id, asset_id, role)`,

  // per-channel posting record — closes the funnel (piece -> channel post -> reach -> leads -> revenue)
  `create table if not exists content_posts (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     content_id bigint references content(id) on delete cascade,
     channel text not null,
     status text not null default 'planned',
     external_url text,
     posted_at timestamptz,
     reach int default 0,
     leads int default 0,
     created_at timestamptz not null default now())`,
  `create index if not exists content_posts_content_idx on content_posts (business_id, content_id, channel)`,
  `create index if not exists content_posts_status_idx on content_posts (business_id, status, posted_at desc)`,

  // ---- CONTENT STUDIO Phase 3 — scheduling + assisted posting + the content funnel.
  // The 8th activation gate: walk connecting a posting channel (YouTube + GBP first,
  // lowest friction; IG/TikTok are the weeks-of-app-review gated future). Data-driven
  // seed mirrors the original 7 rows; on-conflict no-op so it's idempotent.
  `insert into activation (business_id,sort,key,label,status,unlocks,doc_link) values
     (1,8,'social','Connect a posting channel (YouTube → GBP first)','todo','Schedule + assisted posting, then auto-post','strategy/content-studio-architecture.md')
     on conflict (business_id,key) do nothing`,
  // content_posts already exists (Phase 2) — Phase 3 just uses it. Make sure the per-channel
  // uniqueness is enforced so schedule/post upserts can't duplicate a channel row for a piece.
  `create unique index if not exists content_posts_uniq on content_posts (content_id, channel)`,

  // ---- LEAD SCOUT → OPPORTUNITIES. Reddit intercepts (scored + AI-drafted in the crm-api Worker)
  // become a worked pipeline. Additive + idempotent; dedupe key is (business_id, external_id).
  `create table if not exists opportunities (
     id          bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     source      text not null default 'scout',
     external_id text not null,
     subreddit   text,
     link        text,
     title       text,
     score       int,
     tags        jsonb not null default '[]'::jsonb,
     ai_draft    text,
     status      text not null default 'new',
     notes       text,
     posted_at   timestamptz,
     created_at  timestamptz not null default now(),
     updated_at  timestamptz not null default now())`,
  `create unique index if not exists opportunities_business_ext_uq on opportunities (business_id, external_id)`,
  `create index if not exists opportunities_business_status_idx on opportunities (business_id, status, score desc)`,
]

export async function applySchema() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.PGSSL === 'disable' ? false : { rejectUnauthorized: false },
  })
  try {
    let up = false
    for (let i = 0; i < 20 && !up; i++) {
      try { await pool.query('select 1'); up = true }
      catch { await new Promise((r) => setTimeout(r, 3000)) }
    }
    if (!up) { console.error('[schema] DB not reachable — skipping'); return }

    const present = await pool.query("select to_regclass('public.businesses') as t")
    if (!present.rows[0].t) {
      const sql = readFileSync(join(here, '..', '..', 'db', 'schema.sql'), 'utf8')
      await pool.query(sql)
      console.log('[schema] applied + seeded ✓')
    } else {
      console.log('[schema] base present')
    }
    for (const m of MIGRATIONS) {
      try { await pool.query(m) } catch (e) { console.error('[migrate] ' + e.message) }
    }
    console.log('[migrate] done ✓')
  } catch (e) {
    console.error('[schema] error:', e.message)
  } finally {
    await pool.end()
  }
}
