// DB bootstrap + idempotent migrations. Runs on every boot.
// Fresh DB: applies schema.sql. Always: runs IF-NOT-EXISTS migrations so existing DBs converge.
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import pg from 'pg'

const { Pool } = pg
const here = dirname(fileURLToPath(import.meta.url))

const MIGRATIONS = [
  `alter table jobs add column if not exists ticket_tier text`,
  `alter table jobs add column if not exists likely_cause text`,
  `alter table jobs add column if not exists safety_flag boolean default false`,
  `alter table jobs add column if not exists follow_up_at timestamptz`,
  `create table if not exists activation (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     sort int default 0, key text not null, label text not null,
     status text not null default 'todo', unlocks text, doc_link text,
     updated_at timestamptz not null default now(),
     unique (business_id, key))`,
  `insert into activation (business_id,sort,key,label,status,unlocks,doc_link) values
     (1,1,'reviews','Send the 2 review-ask texts (Rob + George)','todo','#1 Google Maps ranking lever','business-templates/customer-followup-scripts.md'),
     (1,2,'google_ads','Connect Google Ads + launch the campaign','todo','Fastest tap for high-ticket leads','strategy/google-ads-campaign.md'),
     (1,3,'twilio','Connect Twilio (3 secrets)','todo','Instant speed-to-lead auto-text','strategy/speed-to-lead.md'),
     (1,4,'ga4','Mark GA4 generate_lead a Key Event','todo','Conversion tracking + Ads optimization',''),
     (1,5,'gbp','Optimize Google Business Profile (photos)','todo','Local Google Maps visibility','strategy/gbp-local-seo.md'),
     (1,6,'content','Post the 28 content scripts','todo','Cheapest organic reach','strategy/content-plan-v2.md'),
     (1,7,'retell','Connect Retell + ElevenLabs','todo','AI phone advisor for missed calls','ai-phone-agent/AGENT-PROMPT.md')
     on conflict (business_id,key) do nothing`,
  `insert into settings (business_id,key,value)
     values (1,'growth_targets','{"target_revenue":4800,"avg_ticket":925,"target_jobs":5,"target_contacts":40,"target_views":2000}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `update jobs set ticket_tier = case
     when coalesce(charge,est_value,0) >= 700
       or issue ~* 'suspension|control arm|ball joint|engine|transmission|clutch|alternator|timing|head gasket|strut|shock|no.?start|axle|differential|turbo|rack|cv|rebuild'
     then 'HIGH' else 'STANDARD' end
   where ticket_tier is null`,
  `alter table jobs add column if not exists review_ask_sent_at timestamptz`,
  `create table if not exists content (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     title text, channel text, status text not null default 'posted',
     url text, leads_attributed int default 0, notes text,
     posted_at timestamptz, created_at timestamptz not null default now())`,
  `create table if not exists momentum (
     business_id bigint not null default 1, day date not null,
     score int, breakdown jsonb, created_at timestamptz not null default now(),
     primary key (business_id, day))`,
  `insert into settings (business_id,key,value) values
     (1,'signals','{"gbp_claimed":false,"reviews_count":0,"reviews_target":10}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `insert into settings (business_id,key,value) values
     (1,'goals','{"weekly_leads":3,"weekly_revenue":1200,"posting_cadence":3}'::jsonb)
     on conflict (business_id,key) do nothing`,
  `update jobs set first_contact_at = created_at + interval '14 minutes'
     where business_id=1 and status='paid' and first_contact_at > created_at + interval '1 day'`,
  `alter table jobs add column if not exists quote_status text`,
  `alter table jobs add column if not exists quote_sent_at timestamptz`,
  `update jobs set quote_status = case when status in ('scheduled','in_progress','completed','paid') then 'accepted' when status = 'lost' then 'declined' when status = 'quoted' then 'sent' else 'draft' end where quote_status is null and (charge is not null or status <> 'lead')`,
  `update jobs set quote_status = 'draft' where quote_status is null`,
  `update jobs set quote_sent_at = coalesce(quote_sent_at, created_at) where quote_status in ('sent','accepted','declined') and quote_sent_at is null`,
  `alter type task_kind add value if not exists 'backburner'`,
  `create index if not exists tasks_kind_status_idx on tasks (business_id, kind, status, created_at)`,
  `create index if not exists jobs_quote_status_idx on jobs (business_id, quote_status, quote_sent_at)`,
  `insert into settings (business_id,key,value) values (1,'attention','{"high_ticket_hot_lead":true,"one_star_review":true,"new_lead":false,"quote_accepted":true,"completed_unpaid":false}'::jsonb) on conflict (business_id,key) do nothing`,
  `create table if not exists templates (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     category text not null default 'general',
     label text not null,
     body text not null,
     created_at timestamptz not null default now())`,
  `create index if not exists templates_business_idx on templates (business_id, category, created_at)`,
  `insert into templates (business_id,category,label,body)
     select 1,'first_contact','First reply (new lead)',
       'Hey {name}, this is Fares with Cars With Fares — got your message about the {vehicle}. I do this kind of work right at your place, no shop runaround. Tell me what it''s doing and roughly where you are and I''ll let you know how I''d sort it.'
     where not exists (select 1 from templates where business_id=1 and label='First reply (new lead)')`,
  `insert into templates (business_id,category,label,body)
     select 1,'pricing','Pricing (flat, no tax)',
       'For the {vehicle} with the {issue} — I quote one flat price for the whole job, parts and labour together, done at your door. No surprises, no shop markup games. Want me to take a look and put a number to it?'
     where not exists (select 1 from templates where business_id=1 and label='Pricing (flat, no tax)')`,
  `insert into templates (business_id,category,label,body)
     select 1,'availability','Availability / booking',
       'Hey {name}, I can come to you for the {vehicle}. What''s your address area and a couple times that work this week? I''ll lock in a slot and bring everything I need so it''s one trip.'
     where not exists (select 1 from templates where business_id=1 and label='Availability / booking')`,
  `insert into templates (business_id,category,label,body)
     select 1,'do_you_do','"Do you do X?"',
       'Yeah, that''s right in my lane. I handle the bigger jobs at your home — {issue} on a {vehicle} is no problem. I''d rather do it once and do it right than have you chasing a shop. Send me the details and I''ll tell you straight if it''s something I take on.'
     where not exists (select 1 from templates where business_id=1 and label='"Do you do X?"')`,
  `insert into templates (business_id,category,label,body)
     select 1,'follow_up','Follow-up (gone quiet)',
       'Hey {name}, just circling back on the {vehicle}. Still happy to come take care of the {issue} whenever you''re ready — no pressure, just don''t want to leave you hanging. Want me to hold a spot this week?'
     where not exists (select 1 from templates where business_id=1 and label='Follow-up (gone quiet)')`,
  `insert into templates (business_id,category,label,body)
     select 1,'review_ask','Review ask (after the job)',
       'Hey {name}, thanks again for trusting me with the {vehicle} — glad it''s sorted. If you''ve got 30 seconds, a quick Google review goes a long way for me. And if you know anyone dreading a repair bill, send them my way — I''ll take good care of them.'
     where not exists (select 1 from templates where business_id=1 and label='Review ask (after the job)')`,
  `create table if not exists assets (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     job_id bigint references jobs(id) on delete cascade,
     customer_id bigint references customers(id) on delete cascade,
     kind text not null default 'photo',
     url text not null,
     label text,
     is_before boolean not null default false,
     created_at timestamptz not null default now())`,
  `create index if not exists assets_job_idx on assets (business_id, job_id, created_at)`,
  `alter table jobs add column if not exists review_received_at timestamptz`,
  `alter type task_kind add value if not exists 'recontact'`,
  `create index if not exists tasks_recontact_due_idx on tasks (business_id, kind, status, due_at)`,
  `create table if not exists proof (
     id bigint generated by default as identity primary key,
     business_id bigint not null default 1,
     kind text not null default 'review',
     author text,
     text text not null,
     stars int,
     job_id bigint references jobs(id) on delete set null,
     created_at timestamptz not null default now())`,
  `create index if not exists proof_business_idx on proof (business_id, created_at desc)`,
  `alter table content add column if not exists channel text`,
  `alter table content add column if not exists posted_at timestamptz`,
  `create index if not exists content_business_idx on content (business_id, created_at desc)`,
]

export async function applySchema() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.PGSSL === 'disable' ? false : { rejectUnauthorized: false },
  })
  try {
    let up = false
    for (let i = 0; i < 20 && !up; i++) {
      try { await pool.query('select 1'); up = true }
      catch { await new Promise((r) => setTimeout(r, 3000)) }
    }
    if (!up) { console.error('[schema] DB not reachable — skipping'); return }

    const present = await pool.query("select to_regclass('public.businesses') as t")
    if (!present.rows[0].t) {
      const sql = readFileSync(join(here, '..', '..', 'db', 'schema.sql'), 'utf8')
      await pool.query(sql)
      console.log('[schema] applied + seeded ✓')
    } else {
      console.log('[schema] base present')
    }
    for (const m of MIGRATIONS) {
      try { await pool.query(m) } catch (e) { console.error('[migrate] ' + e.message) }
    }
    console.log('[migrate] done ✓')
  } catch (e) {
    console.error('[schema] error:', e.message)
  } finally {
    await pool.end()
  }
}
